apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: restaurant
spec:
  selector:
    app: notification-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
