apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-postgres
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-postgres
  template:
    metadata:
      labels:
        app: restaurant-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: restaurant
        - name: POSTGRES_DB
          value: restaurant